# Generated by Django 5.2.7 on 2025-11-02 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('lens', 'HakiLens'), ('draft', 'HakiDraft'), ('review', 'HakiReview'), ('repository', 'HakiDocs')], max_length=20)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('jurisdiction', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('requirements', models.JSONField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('generated_text', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('agent_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('agent_result', models.JSONField(blank=True, default=dict)),
                ('last_story_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('story_id', models.CharField(blank=True, max_length=128, null=True)),
                ('icp_id', models.CharField(blank=True, max_length=128, null=True)),
                ('ipfs_cid', models.CharField(blank=True, max_length=128, null=True)),
                ('dag_tx', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='cases.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
