# Generated by Django 5.2.7 on 2025-11-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_signature_document_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('lens', 'HakiLens'), ('draft', 'HakiDraft'), ('review', 'HakiReview'), ('repository', 'HakiDocs'), ('ip', 'Intellectual Property')], max_length=20),
        ),
    ]
