# Generated by Django 5.2.7 on 2025-11-07 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('documents', '0003_alter_document_doc_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['doc_type', 'category', 'document_type'], name='documents_d_doc_typ_afc6ae_idx'),
        ),
    ]
