import { useEffect } from "react"
import LawyerSidebar from "../components/LawyerSidebar"
import { Wand2, FileText, AlertCircle } from "lucide-react"
import TourGuide from "../components/TourGuide"
import { generateDocument } from "../lib/llm"
import { useProcess } from "../contexts/ProcessContext"

const documentCategories = [
  "General Documents",
  "Litigation",
  "Corporate / Business",
  "Real Estate / Property",
  "Family Law",
  "Succession / Estate",
  "Employment / Labor",
  "Intellectual Property",
  "Immigration",
  "Regulatory / Compliance",
  "Academic / Legal Research",
]

const documentTypesByCategory: Record<string, string[]> = {
  "General Documents": ["Letter of Demand", "Affidavit", "Power of Attorney", "Statutory Declaration"],
  "Litigation": ["Statement of Claim", "Statement of Defense", "Notice of Motion", "Submissions"],
  "Corporate / Business": ["Memorandum of Association", "Articles of Association", "Shareholders Agreement", "Board Resolution"],
  "Real Estate / Property": ["Sale Agreement", "Lease Agreement", "Transfer Documents", "Charge Documents"],
  "Family Law": ["Divorce Petition", "Custody Agreement", "Maintenance Order", "Prenuptial Agreement"],
  "Succession / Estate": ["Will", "Grant of Probate", "Letters of Administration", "Succession Cause"],
  "Employment / Labor": ["Employment Contract", "Termination Letter", "Non-Disclosure Agreement", "Non-Compete Agreement"],
  "Intellectual Property": ["Trademark Application", "Patent Application", "Copyright Assignment", "License Agreement"],
  "Immigration": ["Work Permit Application", "Visa Application", "Citizenship Application", "Appeal Letter"],
  "Regulatory / Compliance": ["Compliance Certificate", "Regulatory Submission", "Audit Report", "Complaint Response"],
  "Academic / Legal Research": ["Legal Opinion", "Research Memorandum", "Case Summary", "Legislative Brief"],
}

export default function HakiDraft() {
  const { getProcessState, updateProcessState } = useProcess()
  const draftState = getProcessState("hakiDraft")
  const {
    showTour,
    category,
    documentType,
    clientName,
    caseType,
    description,
    jurisdiction,
    generating,
    generatedDoc,
    error,
  } = draftState

  useEffect(() => {
    console.log("[HakiDraft] mounted")
    return () => {
      console.log("[HakiDraft] unmounted")
    }
  }, [])

  useEffect(() => {
    console.log("[HakiDraft] state updated", draftState)
  }, [draftState])

  const handleJurisdictionToggle = (country: string) => {
    updateProcessState("hakiDraft", (prev) => {
      const hasCountry = prev.jurisdiction.includes(country)
      const nextJurisdiction = hasCountry
        ? prev.jurisdiction.filter((c) => c !== country)
        : [...prev.jurisdiction, country]

      return {
        ...prev,
        jurisdiction: nextJurisdiction,
      }
    })
  }

  const handleGenerate = async () => {
    if (!category || !documentType || !clientName) {
      alert("Please fill in required fields (Category, Document Type, and Client Name)")
      return
    }

    updateProcessState("hakiDraft", {
      generating: true,
      error: null,
      generatedDoc: "",
    })

    try {
      const prompt = `Generate a professional legal document with the following specifications:

Document Type: ${documentType}
Category: ${category}
Jurisdiction(s): ${jurisdiction.join(", ")}
Client Name: ${clientName}
${caseType ? `Case Type: ${caseType}` : ""}
${description ? `Case Description: ${description}` : ""}

Requirements:
1. Generate a complete, professionally formatted ${documentType} document
2. Include all standard clauses and provisions relevant to ${category}
3. Ensure compliance with ${jurisdiction.join(" and ")} legal requirements
4. Include proper headers, date (${new Date().toLocaleDateString()}), and client information
5. Make the document ready for use by legal professionals
6. Include placeholders where specific details need to be filled in (e.g., [PARTY NAME], [AMOUNT], [DATE])
7. Follow proper legal document structure and formatting

Generate the complete document now:`

      const response = await generateDocument(prompt)

      if (response.error) {
        updateProcessState("hakiDraft", {
          error: response.error,
          generatedDoc: "",
        })
      } else if (response.content) {
        const formattedDoc = `${documentType.toUpperCase()}

Jurisdiction: ${jurisdiction.join(", ")}
Date: ${new Date().toLocaleDateString()}
Client: ${clientName}
${caseType ? `Case Type: ${caseType}` : ""}

${response.content}

---
Generated by HakiDraft AI Document Generator
`

        updateProcessState("hakiDraft", {
          generatedDoc: formattedDoc,
          error: null,
        })
      } else {
        updateProcessState("hakiDraft", {
          error: "No content generated. Please try again.",
          generatedDoc: "",
        })
      }
    } catch (err) {
      updateProcessState("hakiDraft", {
        error:
          err instanceof Error
            ? err.message
            : "An unexpected error occurred. Please check your API configuration.",
        generatedDoc: "",
      })
    } finally {
      updateProcessState("hakiDraft", {
        generating: false,
      })
    }
  }

  return (
    <div className="flex min-h-screen bg-gray-50">
      {showTour && <TourGuide onComplete={() => updateProcessState("hakiDraft", { showTour: false })} />}
      <LawyerSidebar onTourStart={() => updateProcessState("hakiDraft", { showTour: true })} />
      <div className="flex-1 ml-[280px] p-8">
        <div className="max-w-7xl mx-auto">
          <div className="mb-8">
            <div className="flex items-center gap-3 mb-2">
              <div className="w-12 h-12 bg-gradient-to-br from-pink-500 to-purple-600 rounded-lg flex items-center justify-center">
                <Wand2 className="w-6 h-6 text-white" />
              </div>
              <h1 className="text-2xl font-bold text-gray-900">AI Document Generator</h1>
            </div>
            <p className="text-gray-600">Generate professional legal documents with AI assistance</p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            <div className="bg-white rounded-lg shadow-sm p-6 space-y-6">
              <h2 className="text-lg font-semibold text-gray-900">Document Configuration</h2>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Document Category *</label>
                <select
                  value={category}
                  onChange={(e) =>
                    updateProcessState("hakiDraft", {
                      category: e.target.value,
                      documentType: "",
                    })
                  }
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-pink-500"
                >
                  <option value="">Select document category</option>
                  {documentCategories.map((cat) => (
                    <option key={cat} value={cat}>
                      {cat}
                    </option>
                  ))}
                </select>
              </div>

              {category && (
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Document Type *</label>
                  <select
                    value={documentType}
                    onChange={(e) =>
                      updateProcessState("hakiDraft", {
                        documentType: e.target.value,
                      })
                    }
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-pink-500"
                  >
                    <option value="">Select document type</option>
                    {documentTypesByCategory[category]?.map((type) => (
                      <option key={type} value={type}>
                        {type}
                      </option>
                    ))}
                  </select>
                </div>
              )}

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Client Name *</label>
                <input
                  type="text"
                  value={clientName}
                  onChange={(e) => updateProcessState("hakiDraft", { clientName: e.target.value })}
                  placeholder="Enter client full name"
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-pink-500"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Case Type</label>
                <input
                  type="text"
                  value={caseType}
                  onChange={(e) => updateProcessState("hakiDraft", { caseType: e.target.value })}
                  placeholder="e.g., Civil, Criminal, Family Law"
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-pink-500"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Case Description</label>
                <textarea
                  value={description}
                  onChange={(e) => updateProcessState("hakiDraft", { description: e.target.value })}
                  rows={4}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-pink-500"
                ></textarea>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Jurisdiction</label>
                <div className="space-y-2">
                  {["Kenya", "Uganda", "Nigeria", "Ghana"].map((country) => (
                    <label key={country} className="flex items-center">
                      <input
                        type="checkbox"
                        checked={jurisdiction.includes(country)}
                        onChange={() => handleJurisdictionToggle(country)}
                        className="w-4 h-4 text-pink-600 focus:ring-pink-500 border-gray-300 rounded"
                      />
                      <span className="ml-2 text-sm text-gray-700">{country}</span>
                    </label>
                  ))}
                </div>
              </div>

              <button
                onClick={handleGenerate}
                disabled={generating}
                className="w-full py-3 bg-gradient-to-r from-pink-500 to-purple-600 text-white rounded-lg font-medium hover:from-pink-600 hover:to-purple-700 transition disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {generating ? "Generating..." : "Generate Document"}
              </button>
            </div>

            <div className="bg-white rounded-lg shadow-sm p-6">
              <h2 className="text-lg font-semibold text-gray-900 mb-4">Generated Document</h2>
              {error && (
                <div className="mb-4 bg-red-50 border border-red-200 rounded-lg p-4">
                  <div className="flex items-start gap-2">
                    <AlertCircle className="w-5 h-5 text-red-600 flex-shrink-0 mt-0.5" />
                    <div>
                      <h3 className="font-medium text-red-900 mb-1">Generation Error</h3>
                      <p className="text-sm text-red-700">{error}</p>
                      <p className="text-xs text-red-600 mt-2">Please check your API configuration in the .env file.</p>
                    </div>
                  </div>
                </div>
              )}
              {generatedDoc ? (
                <div>
                  <div className="bg-gray-50 border border-gray-200 rounded-lg p-6 max-h-[600px] overflow-y-auto">
                    <pre className="text-sm text-gray-800 whitespace-pre-wrap font-mono">{generatedDoc}</pre>
                  </div>
                  <div className="mt-4 flex gap-3">
                    <button className="flex-1 px-4 py-2 bg-teal-600 text-white rounded-lg hover:bg-teal-700 font-medium">
                      Download PDF
                    </button>
                    <button className="flex-1 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 font-medium">
                      Download DOCX
                    </button>
                    <button
                      onClick={() => updateProcessState("hakiDraft", { generatedDoc: "", error: null })}
                      className="px-4 py-2 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300 font-medium"
                    >
                      Clear
                    </button>
                  </div>
                </div>
              ) : (
                <div className="flex flex-col items-center justify-center py-16 text-center">
                  <FileText className="w-16 h-16 text-gray-400 mb-4" />
                  <h3 className="text-lg font-medium text-gray-900 mb-2">Ready to Generate</h3>
                  <p className="text-sm text-gray-600">Fill in the form and click "Generate Document" to create your legal template.</p>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
